- README.md
- pom.xml
- src/main/java/hng_java_boilerplate/config/DatabaseSeeder.java
- src/main/java/hng_java_boilerplate/organisation/entity/Organisation.java
- src/main/java/hng_java_boilerplate/organisation/repository/OrganisationRepository.java
- src/main/java/hng_java_boilerplate/product/entity/Product.java
- src/main/java/hng_java_boilerplate/product/repository/ProductRepository.java
- src/main/java/hng_java_boilerplate/profile/entity/Profile.java
- src/main/java/hng_java_boilerplate/profile/repository/ProfileRepository.java
- src/main/java/hng_java_boilerplate/user/controller/UserController.java
- src/main/java/hng_java_boilerplate/user/dto/GetUserDto.java
- src/main/java/hng_java_boilerplate/user/entity/User.java
- src/main/java/hng_java_boilerplate/user/repository/UserRepository.java
- src/main/java/hng_java_boilerplate/user/service/UserService.java
- src/main/java/hng_java_boilerplate/util/UUIDGenarator.java
- src/main/resources/application.properties
- src/main/resources/db/migration/V1__init_database.sql
```bash
git clone https://github.com/hngprojects/hng_boilerplate_java_web.git
cd hng_boilerplate_java_web
git checkout chore/database-setup
```
- Ensure you have Java 17 installed.
- Install Maven (or Gradle, depending on your project).
- Ensure PostgreSQL is installed and running.
- Create a new database
`CREATE DATABASE {database_name}`
```
spring.datasource.url=jdbc:postgresql://localhost:5432/your_database_name
spring.datasource.username=your_username
spring.datasource.password=your_password
```
```bash
mvn clean install
mvn spring-boot:run
```
- update the application.properties file to configure flyway
```html
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.user={database_username}
spring.flyway.password={database_password}
```
- Migration …
> implement the database setup task

- .gitignore
- src/main/java/hng_java_boilerplate/exception/GlobalExceptionHandler.java
- src/main/java/hng_java_boilerplate/user/controller/AuthController.java
- src/main/java/hng_java_boilerplate/user/dto/request/LoginDto.java
- src/main/java/hng_java_boilerplate/user/exception/InvalidRequestException.java
- src/main/java/hng_java_boilerplate/user/service/UserService.java
- src/main/java/hng_java_boilerplate/user/serviceImpl/UserServiceImpl.java
- src/test/java/hng_java_boilerplate/user/login_unit_test/UserLoginTest.java
i. Open Postman.
ii. Create a new POST request.
iii. Enter the endpoint URL: http://localhost:8080/api/v1/auth/login
iv. Set the request body type to raw and select JSON from the dropdown.
v. Paste the following JSON into the body:
```
{
"email": "johndoe@example.com",
"password": "Johndo3!"
}
```
vi. Click on the `Send` button.
- **Status Code**: `200 OK`
- **Response Body**:
```json
{
"status_code": 200,
"message": "Login Successful!",
"data": {
"token": "some-token",
"user": {
"id": "some-user-id",
"first_name": "John",
"last_name": "Doe",
"email": "johndoe@example.com",
"created_at": "2024-07-19T20:28:34.399829"
}
}
}
> feat: user-login

- src/main/java/hng_java_boilerplate/metrics/MetricController.java
- src/main/resources/application.properties
Reverts hngprojects/hng_boilerplate_java_web#212
> Revert "Fix: Server fix from previous merge"

- src/main/java/hng_java_boilerplate/profile/entity/Profile.java
- src/main/java/hng_java_boilerplate/user/dto/request/SignupDto.java
- src/main/java/hng_java_boilerplate/user/serviceImpl/UserServiceImpl.java
- src/main/resources/application.properties
Reverts hngprojects/hng_boilerplate_java_web#222
> Revert "Fix: signup update"

- src/main/java/hng_java_boilerplate/plans/controller/PlanController.java
- src/main/java/hng_java_boilerplate/plans/service/PlanService.java
- src/main/java/hng_java_boilerplate/plans/serviceImpl/PlanServiceImpl.java
- src/test/java/hng_java_boilerplate/plan_test/PlanServiceTest.java
Get all subscription plans.
- get all plans.
- get all plans with a user without admin role.
[[FEAT] Get all Subscription Plans](https://github.com/hngprojects/hng_boilerplate_java_web/issues/228)
> Feat: get all plans

- pom.xml
- src/main/java/hng_java_boilerplate/config/WebSecurityConfig.java
- src/main/java/hng_java_boilerplate/user/controller/AuthController.java
- src/main/java/hng_java_boilerplate/user/dto/request/SignupDto.java
- src/main/java/hng_java_boilerplate/util/GoogleJwtUtils.java
- src/main/resources/application.properties
Implementation to login using socials like google OAuth
> feat: create_google-oauth

- src/main/java/hng_java_boilerplate/user/controller/AuthController.java
Reverts hngprojects/hng_boilerplate_java_web#249
> Revert "feat: create_google-oauth"

- .github/workflows/create-application-properties/action.yml
**Changes:**
- **application.properties:**
```properties
rabbitmq.queue.concat=videoConcat
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB
paystack.secret.key=${PAYSTACK}
flutterwave.secret.key=${FLUTTERWAVE}
```
**Testing:**
- **RabbitMQ Configuration:**
- Verified that the RabbitMQ queue configuration is correctly loaded and used in message sending functionality.
- **Multipart File Upload Configuration:**
- Tested file uploads to ensure that the maximum file size and request size limits are correctly enforced.
- **Payment Integration Configuration:**
- Checked that the payment gateway secret keys are correctly read from environment variables and used in payment processing.
**Checklist:**
> [Chore]: Added configs to application.properties

- src/main/java/hng_java_boilerplate/email/EmailServices/EmailTemplateService.java
- src/main/java/hng_java_boilerplate/email/controller/EmailTemplateController.java
- src/main/java/hng_java_boilerplate/email/dto/EmailTemplateRequestDto.java
- src/main/java/hng_java_boilerplate/email/entity/EmailTemplate.java
- src/main/resources/db/migration/V26__update_email_template_table.sql
Get all email templates.
- get all email templates.
[[FEAT] Get all email templates](https://github.com/hngprojects/hng_boilerplate_java_web/issues/357)
> Feat: get all email templates

- pom.xml
- src/main/java/hng_java_boilerplate/user/controller/AuthController.java
- src/main/java/hng_java_boilerplate/user/documentation/User.md
- src/main/java/hng_java_boilerplate/util/GoogleJwtUtils.java
- src/test/java/hng_java_boilerplate/utils/GoogleJwtUtilsTest.java
- **URL**: `/api/v1/auth/google`
- **Method**: `POST`
- **Content-Type**: `application/json`
The `Google login` feature to enhance user engagement and onboarding experience. This feature should include user registration, account creation, and authentication processes using google social oauth service for google account owners.
i. Open Postman.
ii. Create a new POST request.
iii. Enter the endpoint URL: http://localhost:8080/api/v1/auth/google.
iv. Set the request body type to raw and select JSON from the dropdown.
v. Paste the following JSON into the body:
```
{
"access_token": "string",
"expires_in": "integer",
"refresh_token": "string",
"scope": "string",
"token_type": "string",
"id_token": "string",
"expires_at": "long",
"provider": "string",
"type": "string",
"provider_account_id": …
```
> feat: create google login

- src/main/java/hng_java_boilerplate/user/controller/AuthController.java
- src/main/java/hng_java_boilerplate/user/dto/response/OAuthBaseResponse.java
- src/main/java/hng_java_boilerplate/user/dto/response/OAuthUserResponse.java
- src/main/java/hng_java_boilerplate/util/GoogleJwtUtils.java
- src/test/java/hng_java_boilerplate/user/signup_unit_test/UserServiceImplTest.java
- src/test/java/hng_java_boilerplate/utils/FacebookJwtUtilsTest.java
- src/test/java/hng_java_boilerplate/utils/GoogleJwtUtilsTest.java
> fix: update google login

- pom.xml
- src/main/java/hng_java_boilerplate/config/TwoFactorConfig.java
- src/main/java/hng_java_boilerplate/exception/GlobalExceptionHandler.java
- src/main/java/hng_java_boilerplate/twofactor/controller/TwoFactorController.java
- src/main/java/hng_java_boilerplate/twofactor/dtos/TwoFactorResponse.java
- src/main/java/hng_java_boilerplate/twofactor/service/TotpService.java
- src/main/java/hng_java_boilerplate/twofactor/service/TwoFactorService.java
- src/main/java/hng_java_boilerplate/user/entity/User.java
- src/main/java/hng_java_boilerplate/user/service/UserService.java
- src/main/java/hng_java_boilerplate/user/serviceImpl/UserServiceImpl.java
- src/main/resources/db/migration/V27__alter_user_table.sql
Enable 2FA for a user
- enable 2fa for a user.
[[FEAT] Enable 2FA](https://github.com/hngprojects/hng_boilerplate_java_web/issues/120)
> feat: Enable 2fa

- src/main/java/hng_java_boilerplate/jobs/controller/JobListingController.java
- src/main/java/hng_java_boilerplate/jobs/entity/JobListing.java
- src/main/java/hng_java_boilerplate/jobs/service/JobListingService.java
- src/main/java/hng_java_boilerplate/jobs/service/JobListingServiceImpl.java
- src/main/resources/db/migration/V29__create_job_listings_table.sql
**Try accessing the endpoint**
- Implement API endpoint for fetching job listing.
- Job listing should be fetched successfully if it exists.
- Handle unexpected errors and return the appropriate status code.
```json
{
"message": "Job listing",
"status_code": 200,
"data": {
"id": "String",
"title": "String",
"description": "String",
"location": "String",
"salary": "String",
"job_type": "String",
"created_at": "DateTime",
"company_name": "String"
}
}
```
> feat: Implement endpoint to retrieve job listings

- src/main/java/hng_java_boilerplate/jobs/controller/JobListingController.java
- src/main/java/hng_java_boilerplate/jobs/service/JobListingService.java
- src/main/java/hng_java_boilerplate/jobs/service/JobListingServiceImpl.java
**Try accessing the endpoint**
- Send a PUT request to `/api/v1/jobs{id}` to create a job listing.
```json
{
"title": "String",
"description": "String",
"location": "String",
"salary": "String",
"job_type": "String",
"company_name": "String"
}
```
```json
{
"message": "Job listing updated successfully",
"status_code": 200,
"data": {
"id": "String",
"title": "String",
"description": "String",
"location": "String",
"salary": "String",
"job_type": "String",
"created_at": "DateTime",
"company_name": "String"
}
}
```
> feat: add update job listings

- src/main/resources/db/migration/V29__create_job_listings_table.sql
- src/main/resources/db/migration/V33__alter_job_listings_table.sql
Made a fix to alter the job listing migration file properly which was causing errors
> fix: alter migration file properly

- .github/workflows/container-application-properties/action.yml
- .github/workflows/dev-cd.yml
- .github/workflows/prod-cd.yml
- .github/workflows/staging-cd.yml
- .gitignore
- Dockerfile
- docker-compose.production.yml
- docker-compose.staging.yml
- docker-compose.yml
- init-db.sh
- scripts/dev-deploy.sh
- scripts/prod-deploy.sh
- scripts/staging-deploy.sh
> Stephen stage6 task

- pom.xml
- src/main/java/hng_java_boilerplate/comment/controller/CommentController.java
- src/main/java/hng_java_boilerplate/exception/GlobalExceptionHandler.java
- src/main/java/hng_java_boilerplate/user/documentation/User.md
- src/main/java/hng_java_boilerplate/user/entity/VerificationToken.java
- src/main/java/hng_java_boilerplate/user/exception/TokenExpiredException.java
- src/main/java/hng_java_boilerplate/user/repository/VerificationTokenRepository.java
- src/main/java/hng_java_boilerplate/user/service/UserService.java
- src/main/java/hng_java_boilerplate/user/serviceImpl/EmailServiceImpl.java
- src/main/java/hng_java_boilerplate/user/serviceImpl/UserServiceImpl.java
- src/main/resources/db/migration/V34__create_verification_token_table.sql
- src/test/java/hng_java_boilerplate/user/verify_oto_test/UserServiceImplTest.java
- **URL**: `/api/v1/auth/verify-otp`
- **Method**: `POST`
- **Content-Type**: `application/json`
The feature to accept and verify the 6 digit sent to a user to verify email
i. Open Postman.
ii. Create a new POST request.
iii. Enter the endpoint URL: http://localhost:8080/api/v1/auth/verify-otp.
iv. Set the request body type to raw and select JSON from the dropdown.
v. Paste the following JSON into the body:
```
{
"token": "123456"
}
```
vi. Click on the `Send` button.
- **Status Code**: `200 OK`
- **Content-Type**: `application/json`
- **Response Body**:
```json
"Verification Successful"
> feat: verify otp

- .github/workflows/container-application-properties/action.yml
- .github/workflows/dev-cd.yml
- .github/workflows/prod-cd.yml
- .github/workflows/staging-cd.yml
> Codak77 patch 1

- README.md
make una no try this again... nezy and co.
> reverting docker-compose files from codak 3

- .github/workflows/pr-deploy.yml
- .github/workflows/staging-cd-backup.yml
- docker-compose.staging.yml
> [chore]: merge dev to staging

- scripts/staging-deploy.sh
> chore: merge dev to staging

- src/main/java/hng_java_boilerplate/video/controller/VideoController.java
- src/main/java/hng_java_boilerplate/video/dto/DownloadableDTO.java
- src/main/java/hng_java_boilerplate/video/dto/FinishedDTO.java
- src/main/java/hng_java_boilerplate/video/dto/VideoStatusDTO.java
- src/main/java/hng_java_boilerplate/video/entity/VideoSuite.java
- src/main/java/hng_java_boilerplate/video/errorhandler/VideoErrorHandler.java
- src/main/java/hng_java_boilerplate/video/service/VideoServiceConsumer.java
- src/main/java/hng_java_boilerplate/video/service/VideoServiceImpl.java
- src/main/java/hng_java_boilerplate/video/service/VideoServicePublisher.java
- src/main/java/hng_java_boilerplate/video/utils/VideoMapper.java
- src/main/java/hng_java_boilerplate/video/utils/VideoUtils.java
- src/main/java/hng_java_boilerplate/video/videoEnums/JobType.java
- src/main/resources/db/migration/V36__alter_video_table.sql
- src/test/java/hng_java_boilerplate/video/ConcatVideoTest.java
- src/test/java/hng_java_boilerplate/video/VideoUtilsTest.java
**Description:**
- RefactoredVideo to improve reusabilty.
**Changes:**
- Entity
- VideoUtils
- videoService impl
**Testing:**
-all unit test passed.
> [Refactor] :Refactor video package

- src/main/java/hng_java_boilerplate/exception/GlobalExceptionHandler.java
- src/main/java/hng_java_boilerplate/jobs/exceptions/CustomExceptionHandler.java
- src/main/java/hng_java_boilerplate/profile/errorHandlers/ProfileErrorHandler.java
**Description**:
This PR refactors the `ExceptionHandler` class to improve its structure and consistency. The key changes include:
- **Consolidation**: Merged similar exception handling methods to reduce code duplication.
- **Readability**: Improved code readability and maintainability by simplifying complex logic.
**Changes**:
- Refactored error handling methods in the `ExceptionHandler` class.
**Testing**:
- Verified that all existing unit and integration tests pass.
> {Feat]: Refactor and Clean Up ExceptionHandler Class

- src/main/java/hng_java_boilerplate/config/WebSecurityConfig.java
- src/main/java/hng_java_boilerplate/payment/dtos/PaymentRequestBody.java
- src/main/java/hng_java_boilerplate/payment/entity/Payment.java
- src/main/java/hng_java_boilerplate/payment/service/PaymentService.java
- src/main/java/hng_java_boilerplate/payment/utils/FulfillCheckout.java
- src/main/java/hng_java_boilerplate/user/entity/User.java
- src/main/java/hng_java_boilerplate/user/serviceImpl/UserServiceImpl.java
- src/main/resources/db/migration/V37__update_payment.sql
- src/test/java/hng_java_boilerplate/user/signup_unit_test/UserServiceImplTest.java
> fix: cors error
